[tools]
python = "3.11.1"
lua = "5.2.4"
node = "18"
zoxide = "latest"
awscli = "latest"
ripgrep = "latest"
fzf = "latest"
cmake = "latest"
terraform = "latest"
"cargo:starship" = "latest"
"cargo:bob-nvim" = "latest"
"npm:neovim" = "latest"

[settings]
experimental = true
