[tools]
python = "3.11.1"
lua = "5.2.4"
node = "20.17.0"
zoxide = "latest"
awscli = "latest"
ripgrep = "latest"
terraform = "latest"
"cargo:starship" = "latest"
"cargo:bob-nvim" = "latest"
"npm:neovim" = "latest"
go = "1.24"
protoc = "latest"
github-cli = "latest"
yarn = "1"
pnpm = "9.5.0"
jq = "latest"
azure-cli = "latest"
java = "latest"
bun = "latest"
elixir = "1.17.3"
erlang = "27.1.2"
helm = "latest"
kubectl = "latest"
argocd = "latest"
maven = "3.9.9"

[settings]
experimental = true
python_compile = true
