[tools]
python = "3.11.1"
lua = "5.1"
node = "20.17.0"
zoxide = "latest"
awscli = "latest"
ripgrep = "latest"
terraform = "latest"
"cargo:starship" = "latest"
"cargo:bob-nvim" = "latest"
"npm:neovim" = "latest"
go = "latest"
protoc = "latest"
github-cli = "latest"
yarn = "1"
pnpm = "9.5.0"
jq = "latest"
azure-cli = "latest"
java = "latest"
bun = "latest"

[settings]
experimental = true
python_compile = true
