version: 2
root-markers:
  - .git/

tools:
  prettier: &prettier
    format-command: '/Users/dk8ChNoe/.asdf/installs/nodejs/17.6.0/bin/node /Users/dk8ChNoe/.asdf/installs/nodejs/17.6.0/.npm/bin/prettierd ${INPUT}'
    format-stdin: true

  mix_credo: &mix_credo
    lint-command: "MIX_ENV=test mix credo suggest --format=flycheck --read-from-stdin ${INPUT}"
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %t: %m'
      - '%f:%l: %t: %m'
    lint-category-map:
      R: N
      D: I
      F: E
      W: W
    root-markers:
      - mix.lock
      - mix.exs

languages:
  elixir:
    - <<: *mix_credo
  javascript:
    - <<: *prettier
  typescript:
    - <<: *prettier
  javascriptreact:
    - <<: *prettier
  typescriptreact:
    - <<: *prettier
  json: 
    - <<: *prettier
