"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_orange)\
$username\
$hostname\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
$git_state\
[](fg:color_aqua bg:color_bg1)\
$memory_usage\
$cmd_duration\
[ ](fg:color_bg1)\
$line_break$character"""



palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user]($style)'

[hostname]
style = "bg:color_orange fg:color_fg0"
ssh_only = false
ssh_symbol = " "
format = '[@$ssh_symbol$hostname ]($style)'


[directory]
style = "fg:color_fg0 bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_aqua)]($style)'

[git_state]
style = "bg:color_aqua"
format = '[[ $state( $progress_current/$progress_total) ](fg:color_fg0 bg:color_aqua)]($style)'

[cmd_duration]
min_time = 0
format = "[ $duration ]($style)"
style = "bg:color_bg1 fg:color_fg0"

[memory_usage]
disabled = false
threshold = 0
style = "bg:color_bg1 fg:color_fg0"
format = '[ $symbol${ram_pct} ]($style)'
symbol = " "

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
